task2/lib/task2_web/router.ex
defmodule Task2Web.Router do
  use Task2Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug Task2.Plugs.GetCurrentUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Task2Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController do
      get "/complete", TaskController, :complete, as: :complete
    end
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", Task2Web do
    pipe_through :api
    resources "/timeblocks", TimeblockController, except: [:new, :edit]
  end
end

task2/lib/task2/accounts/user.ex
defmodule Task2.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Task2.Accounts.User


  schema "users" do
    field :email, :string
    field :name, :string
    belongs_to :manager, User
    has_many :subordinates, User, foreign_key: :manager_id

    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:email, :name, :manager_id])
    |> validate_required([:email, :name])
  end
end

task2/lib/task2_web/controllers/user_controller.ex
defmodule Task2Web.UserController do
  use Task2Web, :controller

  alias Task2.Accounts
  alias Task2.Accounts.User
  alias Task2.Social

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    user_id_list = Accounts.get_all_id()
    user_id_list = [0 | user_id_list]
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset, user_id_list: user_id_list)
  end

  def create(conn, %{"user" => user_params}) do
    if Map.get(user_params, "manager_id") == "0" do
        user_params = Map.delete(user_params, "manager_id")
    end
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: page_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    tasks = Social.get_tasks_posted(id)
    render(conn, "show.html", user: user, tasks: tasks)
  end

  def edit(conn, %{"id" => id}) do
    user_id_list = Accounts.get_all_id()
    user_id_list = [0 | user_id_list]
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset, user_id_list: user_id_list)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

task2/lib/task2_web/views/user_view.ex
defmodule Task2Web.UserView do
  use Task2Web, :view
end

task2/lib/task2_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

task2/lib/task2_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :manager,"Manager (Choose 0 if you do not have a manager)", class: "control-label" %>
    <%= select f, :manager_id, @user_id_list, class: "form-control" %>
    <%= error_tag f, :manager_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

task2/lib/task2_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.name %></td>

      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: user_path(@conn, :new) %></span>

task2/lib/task2_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

task2/lib/task2_web/templates/user/show.html.eex
<div class="row">
  <div class="col-3">
    <h2>My Profile</h2>
    <ul>
      <li>
        <strong>Email:</strong>
        <%= @user.email %>
      </li>

      <li>
        <strong>Name:</strong>
        <%= @user.name %>
      </li>

      <li>
        <strong>Manager:</strong>
        <%= if @user.manager do %>
          <%=  @user.manager.name %>
        <% end %>
      </li>

      <li>
        <strong>Subordinates:</strong>
        <ul>
          <%= for subordinate <- @user.subordinates do %>
            <li><%= subordinate.name %></li>
          <% end %>
        </ul>
      </li>

    </ul>
    <%= if @current_user.id == @user.id do %>
       <%= button "New Task", to: task_path(@conn, :new), method: :get, class: "btn btn-primary " %>
    <% end %>
    <%= button "Edit", to: user_path(@conn, :edit, @user), method: :get, class: "btn btn-warning" %>
    <%= button "Back", to: task_path(@conn, :index), method: :get, class: "btn btn-info" %>
  </div>
  <div class="col-9">
    <h2>Tasks You Posted</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Status</th>
          <th>Title</th>
          <th>Assignee</th>
          <th>Time</th>

          <th></th>
        </tr>
      </thead>
      <tbody>
    <%= for task <- @tasks do %>
        <tr>
          <td id="status">
            <%= if task.time do %>
              Completed
            <% end %>
          </td>
          <td><%= task.title %></td>

          <td>
            <%= if task.user_id == @current_user.id do %>
              <b id="notice"><%= task.user.name %></b>
            <% else %>
              <%= task.user.name %>
            <% end %>
          </td>
          <td>
          <%= if task.time do %>
            <span><%= task.time %></span><span> minutes</span>
          <% else %>
          <% end %>
          </td>

          <td class="text-right">
            <%= if @current_user.id == task.user_id do %>
              <span><%= link "Complete", to: task_complete_path(@conn, :complete, task), class: "btn btn-default btn-xs" %></span>
            <% end %>
            <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
            <%= if @current_user.id == task.creater_id do %>
            <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
            <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
            <% end %>
          </td>
        </tr>
    <% end %>
      </tbody>
    </table>
  </div>
</div>